version: "3.7"

services:
  redis:
    image: redis

  gcc-medical-tracker:
    image: ${REGISTRY}/${IMAGETAG}:${GO_REVISION}
    env_file: env_vars/${GO_STAGE_NAME}.env
    environment:
      NODE_ENV: ${GO_STAGE_NAME}
      AUTH_KEY: ${AUTH_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_PWD: ${DB_PWD}
      DB_USER: ${DB_USER}
      ENABLE_SSL: ${ENABLE_SSL}
