version: "3.7"

networks:
  default:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}

services:
  redis:
    image: redis
    networks:
      - default

  gcc-medical-tracker:
    image: ${REGISTRY}/${IMAGETAG}:${GO_REVISION}
    env_file: env_vars/${GO_STAGE_NAME}.env
    environment:
      NODE_ENV: ${GO_STAGE_NAME}
      AUTH_KEY: ${AUTH_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_PWD: ${DB_PWD}
      DB_USER: ${DB_USER}
      ENABLE_SSL: ${ENABLE_SSL}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - traefik
      - default
    deploy:
      replicas: ${NUMBER_REPLICAS}
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: ${SERVICE_RESTART_CONDITION}
        delay: 10s
      labels:
        - traefik.frontend.rule=${TRAEFIK_FRONTEND_HOST}
        - traefik.enable=true
        - traefik.port=${TRAEFIK_PORT}
        - traefik.docker.network=${TRAEFIK_NETWORK}
        # Traefik service that listens to HTTP
        #- traefik.redirectorservice.frontend.entryPoints=http
        #- traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        #- traefik.webservice.frontend.entryPoints=https
